### ISSUE TITLE
Deep Learning A practioner's approche

### ISSUE THREAD

**Issue by AmelBENAIDA** [IsaacChanghau/DL-NLP-Readings#1]
After downloading the file, I am not able to open it. I get the error
Could not open "Deep Learning a Practitioners Approach.pdf"
Archive not supported

**Comment by 26hzhang** [comment]
@AmelBENAIDA could you pls download it again? I tried on my side just now, and I can open it actually.

**Comment by AmelBENAIDA** [comment]
Thank you, it works.
Thank you for all what you are sharing & for reply
